project:
  type: website
  output-dir: docs
  
output:
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 2
    theme: cosmo
    highlight: tango
    df_print: paged
    lib_dir: site_libs
    self_contained: no
    includes:
     in_header: "favicon.html"
# All icons were obtained from https://icons.getbootstrap.com/
website:   
  page-navigation: true
  title: "MTH 142:Intro to Statistics Files"
  
  navbar:
 
    left:
    - text: Resources
      href: Resources.qmd
    - icon: book 
      href: https://mdsr-book.github.io/mdsr2e/
    - text: T & T
      href: https://moderndive.com/C-appendixC.html
    - text: R
      href: http://hcc-rstudiosrv1.hcc.edu:8787/auth-sign-in
    
    right:
    - icon: github
      href: https://github.com/Nics-Github/MTH_142
    - text: email
      href: nschwab@hcc.edu
  
    - text: Syllabus
      href: https://www.google.com

  
  page-footer:
    right: 
    - text: credits
      href: credits.qmd
      
