{
  "hash": "85bc8de1247f29a6d7fbf94f6f90e4fa",
  "result": {
    "markdown": "---\ntitle: \"Tutorial\"\noutput: learnr::tutorial\nruntime: shiny_prerendered\n---\n\n\n\n\n## Introduction\n\nIn this Rtutorial we will use a famous dataset from one of the first modern statisticians, John Arbuthnot. We will also discuss how to make a proportion hypothesis test with a data set. This is the first of several types of hypothesis tests we will carry out in the second half of the semester.\n\n## Randomly choose a data point\n\n1.  In the setup chunk of `library(mosaic)` and `library(openintro)`. Read about the arbuthnot data frame in openintro with `?arbuthnot`, feel free to read a bit about John Arbuthnot [here](https://en.wikipedia.org/wiki/John_Arbuthnot).\n\n\n::: {.cell exercise='true' exercise.eval='false'}\n<div class=\"tutorial-exercise\" data-label=\"libraries-view\" data-caption=\"Code\" data-completion=\"1\" data-diagnostics=\"1\" data-startover=\"1\" data-lines=\"0\">\n\n```{.r .cell-code}\n?arbuthnot\n```\n\n<script type=\"application/json\" data-opts-chunk=\"1\">{\"fig.width\":7,\"fig.height\":5,\"fig.retina\":2,\"fig.align\":\"default\",\"fig.keep\":\"high\",\"fig.show\":\"asis\",\"out.width\":672,\"warning\":true,\"error\":false,\"message\":true,\"exercise.df_print\":\"default\",\"exercise.checker\":\"NULL\"}</script></div>\n:::\n\n\n2.  Type `View(arbuthnot)` in the chunk above.\n\n3.  Compute the proportion of girls born in a random year of John Arbuthnot's observations. Let's randomly choose a year from the data to use as our hypothesis test with `sample(nrow(arbuthnot),1)` \\*\n\n\n::: {.cell exercise='true'}\n<div class=\"tutorial-exercise\" data-label=\"random-number\" data-caption=\"Code\" data-completion=\"1\" data-diagnostics=\"1\" data-startover=\"1\" data-lines=\"0\">\n\n```{.r .cell-code}\nsample(nrow(arbuthnot),1)\n```\n\n<script type=\"application/json\" data-opts-chunk=\"1\">{\"fig.width\":7,\"fig.height\":5,\"fig.retina\":2,\"fig.align\":\"default\",\"fig.keep\":\"high\",\"fig.show\":\"asis\",\"out.width\":672,\"warning\":true,\"error\":false,\"message\":true,\"exercise.df_print\":\"default\",\"exercise.checker\":\"NULL\"}</script></div>\n:::\n\n\n4.  Now you can take the random number and tell R you want to look only at that row in the dataset. I'll choose the 1st year of the dataset by typing `arbuthnot[1,]`. Change the 1 to your random number in the chunk below. (Every time you knit or render your document the random number from the code above will change, so just type it out the first time and delete the code.)\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 3\n   year  boys girls\n  <int> <int> <int>\n1  1629  5218  4683\n```\n:::\n:::\n\n\n5.  Calculate the proportion of girls born in London in your year. You can do this with division. Mine would be\n\n    $\\frac{4683}{5218+4683}=\\frac{4683}{9901}=0.4729$\n\n    or 47%.\n\n\\* You will not need the `sample()` or `nrow()` functions after this assignment. If you are interested in what this code is doing here's a quick description: `nrow()` counts the number of rows in the `arbuthnot` set. `sample()` randomly chooses a value between 0 and up to the number of rows in the `arbuthnot` set. The 1 is telling how many random numbers to generate.\n\n## Set up the hypothesis test\n\n1.  Set up and conduct a hypothesis tests using `prop.test()`. Specifically you should check:\n\n-   The success-failure condition (There are at least 10 success and 10 failures)\n\n-   Independence\n\n-   The data comes from a random sample.\n\n2.  Set up the hypothesis test notation. Put \\$ \\$ around the text below, be sure to type it in the white space not a code chunk.\n\nH_0: p = 0.5\n\nH_1: p \\\\ne 0.5\n\n3.  Choose a cut-off value $\\alpha$ . In most of the homework problems 0.05 is appropriate. Show your alpha by putting \\$ \\$ around the text below.\n\n    \\alpha = 0.05\n\n## Execute the test\n\nNow we'll have R generate the output of the test with `prop.test()`. This is very similar to making a confidence interval except we have two new arguments:\n\n-   what we think the null proportion is, `p=0.5`\n\n-   what the alternative hypothesis is, `alternative = \"two.sided\"`.\n\nA success is a girl born. 4683 girls were born out of 9901 births in 1629 so my set up is:\n\n\n::: {.cell exercise='true'}\n<div class=\"tutorial-exercise\" data-label=\"prop-test\" data-caption=\"Code\" data-completion=\"1\" data-diagnostics=\"1\" data-startover=\"1\" data-lines=\"0\">\n\n```{.r .cell-code}\nprop.test(x=4683,n=9901,p=0.5,alternative =\"two.sided\", correct=\"False\")\n```\n\n<script type=\"application/json\" data-opts-chunk=\"1\">{\"fig.width\":7,\"fig.height\":5,\"fig.retina\":2,\"fig.align\":\"default\",\"fig.keep\":\"high\",\"fig.show\":\"asis\",\"out.width\":672,\"warning\":true,\"error\":false,\"message\":true,\"exercise.df_print\":\"default\",\"exercise.checker\":\"NULL\"}</script></div>\n:::\n\n\nNote: The p-value is 7.587e-08. This is scientific notation for 0.00000007587. You can tell R not to use scientific notation by adding `options(scipen=10)` to your setup chunk. Put it in the code chunk above and rerun the test to see the difference.\n\nOptional: There is a lot of extra text in the output. If we want to clean it up we can first save the results of the prop.test() then call just the p-value. See the chunk below:\n\n\n::: {.cell exercise='true'}\n<div class=\"tutorial-exercise\" data-label=\"optional\" data-caption=\"Code\" data-completion=\"1\" data-diagnostics=\"1\" data-startover=\"1\" data-lines=\"0\">\n\n```{.r .cell-code}\nprop_test_results <- prop.test(x=4683,n=9901,p=0.5,alternative =\"two.sided\", correct=\"False\")\nprop_test_results$p.value\n```\n\n<script type=\"application/json\" data-opts-chunk=\"1\">{\"fig.width\":7,\"fig.height\":5,\"fig.retina\":2,\"fig.align\":\"default\",\"fig.keep\":\"high\",\"fig.show\":\"asis\",\"out.width\":672,\"warning\":true,\"error\":false,\"message\":true,\"exercise.df_print\":\"default\",\"exercise.checker\":\"NULL\"}</script></div>\n:::\n\n\nThe dollar sign operator `$` takes out a named element from a list. For example if you type: `arbuthnot$year` every year that data was collected will be displayed. Using the code above only your p.value will be displayed which just looks better.\n\n## Conclusion\n\nWe now have to compare $\\alpha$ and the p-value. We choose $\\alpha$ to say any probability less than \\alpha is unlikely if the null hypothesis is true. My p-value of 0.000000076 is much less than the alpha of 0.05. So I believe, based on this one randomly chosen value, that it is unlikely that the proportion of girls born in any year in 17th century London is 0.5 and I believe the number to be different.\n\nIt is possible that a type 1 error has occurred and I've rejected the null hypothesis even though it is true. But without further sampling it is impossible for me to know if that is the case.\n\n## A few notes on our test.\n\nConfusingly there are many different methods for computing p-values, all of which can be done in R. The method we will use in this class is `prop.test(x,n,p=,correct=FALSE)`. See the cheat sheet. You will use this in your assignment for this tutorial (and for your homework chapter 6).\n\nAlso we usually wouldn't have the data from multiple years, we might just have data from one sample and try to estimate `p` from that. Most people will find that more boys than girls are born. This is hypothesized to happen because boys are more likely to die before reproductive age. Eventually the proportions of males to females settle closer to 50:50 as reproductive age gets closer. By chance some of you will find that the proportions are equal and you will not reject the null hypothesis.\n\n## The three p's\n\nThere are three p's we need to keep separate:\n\n-   p - This is the population parameter, it is the value we are constantly trying to estimate.\n\n-   $\\hat{p}$ - This is the population statistic, it is the value we use as an estimate for p.\n\n-   p-value - This is the probability that our population statistic is possible if the null hypothesis is correct.\n\nI feel bad about the all the p's.\n\n## Assignment\n\nAssignment 5 pts.\n\nYou are to conduct a bare bones hypothesis test in R with data from a random year in the table.\n\n-   Choose a random year to use as your proportion.\n\n-   You cannot use the first year (1629).\n\n-   Output your test an html file from an R Markdown file. I have posted a skeleton Rmarkdown for you to use.\n\n-   Post the html output of your Rmarkdown file to the forum. See the video and my output for the format.\n\npreserve0a22a4d9dc17b7f5\npreservee27cfbf29b798165\npreservec7e38b28fa2faaea\npreserve43ebb5ed83713983\npreserve37c309dc85a385aa\npreserve5d35b5b7d6339530\npreservebd24a9aaf1df5951\npreservef8d61764ac08ec75\n\n<!--html_preserve-->\n<script type=\"application/shiny-prerendered\" data-context=\"dependencies\">\n{\"type\":\"list\",\"attributes\":{},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquery\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"3.6.0\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/3.6.0\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquery-3.6.0.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"jquerylib\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.1.4\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"font-awesome\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"5.1.0\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"rmd/h/fontawesome\"]}]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"css/all.css\",\"css/v4-shims.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"rmarkdown\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"2.16\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"bootbox\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"4.4.0\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/bootbox\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"bootbox.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.10.1\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"idb-keyvalue\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"3.2.0\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/idb-keyval\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"idb-keyval-iife-compat.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[false]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.10.1\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tutorial\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.10.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/tutorial\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"tutorial.js\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"tutorial.css\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.10.1\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tutorial-autocompletion\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.10.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/tutorial\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"tutorial-autocompletion.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.10.1\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tutorial-diagnostics\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.10.1\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/tutorial\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"tutorial-diagnostics.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.10.1\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.2.6\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/ace\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.10.1\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboardjs\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.5.15\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/clipboardjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboard.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.10.1\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.2.6\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/ace\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.10.1\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboardjs\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.5.15\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/clipboardjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboard.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.10.1\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.2.6\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/ace\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.10.1\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboardjs\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.5.15\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/clipboardjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboard.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.10.1\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.2.6\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/ace\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ace.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.10.1\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"version\",\"src\",\"meta\",\"script\",\"stylesheet\",\"head\",\"attachment\",\"package\",\"all_files\",\"pkgVersion\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"html_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboardjs\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"1.5.15\"]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"file\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"lib/clipboardjs\"]}]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"clipboard.min.js\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"learnr\"]},{\"type\":\"logical\",\"attributes\":{},\"value\":[true]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.10.1\"]}]}]}\n</script>\n<!--/html_preserve-->\n<!--html_preserve-->\n<script type=\"application/shiny-prerendered\" data-context=\"execution_dependencies\">\n{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"packages\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"packages\",\"version\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"data.frame\"]},\"row.names\":{\"type\":\"integer\",\"attributes\":{},\"value\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"airports\",\"assertthat\",\"backports\",\"base\",\"broom\",\"cherryblossom\",\"cli\",\"colorspace\",\"compiler\",\"crosstalk\",\"datasets\",\"DBI\",\"digest\",\"dplyr\",\"ellipsis\",\"evaluate\",\"fansi\",\"farver\",\"fastmap\",\"forcats\",\"generics\",\"ggdendro\",\"ggforce\",\"ggformula\",\"ggplot2\",\"ggrepel\",\"ggridges\",\"ggstance\",\"glue\",\"graphics\",\"grDevices\",\"grid\",\"gridExtra\",\"gtable\",\"haven\",\"hms\",\"htmltools\",\"htmlwidgets\",\"httpuv\",\"jquerylib\",\"jsonlite\",\"knitr\",\"labelled\",\"later\",\"lattice\",\"leaflet\",\"learnr\",\"lifecycle\",\"magrittr\",\"markdown\",\"MASS\",\"Matrix\",\"methods\",\"mime\",\"mosaic\",\"mosaicCore\",\"mosaicData\",\"munsell\",\"openintro\",\"pillar\",\"pkgconfig\",\"plyr\",\"polyclip\",\"promises\",\"purrr\",\"R6\",\"Rcpp\",\"readr\",\"rlang\",\"rmarkdown\",\"rprojroot\",\"rstudioapi\",\"scales\",\"shiny\",\"splines\",\"stats\",\"stringi\",\"stringr\",\"tibble\",\"tidyr\",\"tidyselect\",\"tools\",\"tweenr\",\"tzdb\",\"usdata\",\"utf8\",\"utils\",\"vctrs\",\"withr\",\"xfun\",\"xtable\",\"yaml\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"0.1.0\",\"0.2.1\",\"1.4.1\",\"4.2.0\",\"1.0.1\",\"0.1.0\",\"3.4.0\",\"2.0-3\",\"4.2.0\",\"1.2.0\",\"4.2.0\",\"1.1.3\",\"0.6.29\",\"1.0.10\",\"0.3.2\",\"0.16\",\"1.0.3\",\"2.1.1\",\"1.1.0\",\"0.5.2\",\"0.1.3\",\"0.1.23\",\"0.3.3\",\"0.10.1\",\"3.3.6\",\"0.9.1\",\"0.5.3\",\"0.3.5\",\"1.6.2\",\"4.2.0\",\"4.2.0\",\"4.2.0\",\"2.3\",\"0.3.1\",\"2.5.1\",\"1.1.2\",\"0.5.3\",\"1.5.4\",\"1.6.6\",\"0.1.4\",\"1.8.0\",\"1.40\",\"2.9.1\",\"1.3.0\",\"0.20-45\",\"2.1.1\",\"0.10.1\",\"1.0.2\",\"2.0.3\",\"1.1\",\"7.3-58\",\"1.4-1\",\"4.2.0\",\"0.12\",\"1.8.3\",\"0.9.0\",\"0.20.2\",\"0.5.0\",\"2.3.0\",\"1.8.1\",\"2.0.3\",\"1.8.7\",\"1.10-0\",\"1.2.0.1\",\"0.3.4\",\"2.5.1\",\"1.0.9\",\"2.1.2\",\"1.0.5\",\"2.16\",\"2.0.3\",\"0.14\",\"1.2.1\",\"1.7.2\",\"4.2.0\",\"4.2.0\",\"1.7.8\",\"1.4.1\",\"3.1.8\",\"1.2.1\",\"1.1.2\",\"4.2.0\",\"1.0.2\",\"0.3.0\",\"0.2.0\",\"1.2.2\",\"4.2.0\",\"0.4.1\",\"2.5.0\",\"0.33\",\"1.8-4\",\"2.3.5\"]}]}]}\n</script>\n<!--/html_preserve-->",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {
      "preserve0a22a4d9dc17b7f5": "\n<script type=\"application/shiny-prerendered\" data-context=\"server-start\">\nlibrary(learnr)\nlibrary(mosaic)\nlibrary(openintro)\nknitr::opts_chunk$set(echo = FALSE)\n</script>\n",
      "preserve37c309dc85a385aa": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\n`tutorial-exercise-random-number-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-random-number-code-editor`)), session)\noutput$`tutorial-exercise-random-number-output` <- renderUI({\n  `tutorial-exercise-random-number-result`()\n})\n</script>\n",
      "preserve43ebb5ed83713983": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\n`tutorial-exercise-libraries-view-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-libraries-view-code-editor`)), session)\noutput$`tutorial-exercise-libraries-view-output` <- renderUI({\n  `tutorial-exercise-libraries-view-result`()\n})\n</script>\n",
      "preserve5d35b5b7d6339530": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\n`tutorial-exercise-prop-test-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-prop-test-code-editor`)), session)\noutput$`tutorial-exercise-prop-test-output` <- renderUI({\n  `tutorial-exercise-prop-test-result`()\n})\n</script>\n",
      "preservebd24a9aaf1df5951": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\n`tutorial-exercise-optional-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-optional-code-editor`)), session)\noutput$`tutorial-exercise-optional-output` <- renderUI({\n  `tutorial-exercise-optional-result`()\n})\n</script>\n",
      "preservec7e38b28fa2faaea": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nsession$onSessionEnded(function() {\n        learnr:::session_stop_event(session)\n      })\n</script>\n",
      "preservee27cfbf29b798165": "\n<script type=\"application/shiny-prerendered\" data-context=\"server\">\nlearnr:::register_http_handlers(session, metadata = NULL)\n</script>\n",
      "preservef8d61764ac08ec75": "\n<script type=\"application/shiny-prerendered\" data-context=\"server-extras\">\nojs_define <- function(..., .session = shiny::getDefaultReactiveDomain()) {\n  quos <- rlang::enquos(...)\n  vars <- rlang::list2(...)\n  nm <- names(vars)\n  if (is.null(nm)) {\n    nm <- rep_len(\"\", length(vars))\n  }\n  mapply(function(q, nm, val) {\n    # Infer name, if possible\n    if (nm == \"\") {\n      tryCatch({\n        nm <- rlang::as_name(q)\n      }, error = function(e) {\n        code <- paste(collapse = \"\\n\", deparse(rlang::f_rhs(q)))\n        stop(\"ojs_define() could not create a name for the argument: \", code)\n      })\n    }\n    .session$output[[nm]] <- val\n    outputOptions(.session$output, nm, suspendWhenHidden = FALSE)\n    .session$sendCustomMessage(\"ojs-export\", list(name = nm))\n    NULL\n  }, quos, nm, vars, SIMPLIFY = FALSE, USE.NAMES = FALSE)\n  invisible()\n}\n</script>\n"
    },
    "postProcess": true
  }
}